<a href="https://colab.research.google.com/github/akshat-diwan/Machine-Learning/blob/main/Spam_Mail_Prediction(Logistic_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Author  
**Abhishek Mishra**

* 🔗 LinkedIn - https://www.linkedin.com/in/abhishekmishraai/

* 📺 YouTube - https://www.youtube.com/@abhishekmishraai

* Github - https://github.com/abhishekmishraai

# Spam Mail Prediction

**Import Dependancy**

In [ ]:
# Import Dependancy
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score
from sklearn.feature_extraction.text import TfidfVectorizer

**Import the mail data**

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Toppers Acadmy Data/data/Machine Learning/Chapter 5:- Natural language processing(NLP)/Project/Copy of mail_data.csv')

In [ ]:
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [ ]:
df['Category'].value_counts()

,count
Category,
ham,4825
spam,747


### Dealing with null values

**Replacing null values with null string**

In [ ]:
df.isnull().sum()

,0
Category,0
Message,0


### Lable Encoding

*   ham	converted as 1
*   spam converted as 0



In [ ]:
df['label'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df['label'].value_counts()

,count
label,
0,4825
1,747


### Train Test Split

**Sepret data as x and y**

In [ ]:
x = df['Message']
y = df['label']

In [ ]:
x

,Message
0,"Go until jurong point, crazy.. Available only ..."
1,Ok lar... Joking wif u oni...
2,Free entry in 2 a wkly comp to win FA Cup fina...
3,U dun say so early hor... U c already then say...
4,"Nah I don't think he goes to usf, he lives aro..."
...,...
5567,This is the 2nd time we have tried 2 contact u...
5568,Will ü b going to esplanade fr home?
5569,"Pity, * was in mood for that. So...any other s..."
5570,The guy did some bitching but I acted like i'd...


In [ ]:
y

,label
0,0
1,0
2,1
3,0
4,0
...,...
5567,1
5568,0
5569,0
5570,0


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=3)

### Feature Extraction

**convert text data into numerical data**

In [ ]:
feature_extraction = TfidfVectorizer(min_df=1, stop_words='english', lowercase=True)
x_train = feature_extraction.fit_transform(x_train)
x_test = feature_extraction.transform(x_test)



### Create model

**Logistic regression**

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [ ]:
train_pred[:5]

array([0, 0, 0, 0, 1])

In [ ]:
y_train.head()

,label
3075,0
1787,0
1614,0
4304,0
3266,1


In [ ]:
test_pred[:5]

array([1, 0, 0, 0, 0])

In [ ]:
y_test.head()

,label
2632,1
454,0
983,1
1282,0
4610,0


### Eveluating the training model

**Prediction score on training data**

In [ ]:
print('train accu :- ',accuracy_score(y_train,train_pred))
print('train confusion matrix :- \n',confusion_matrix(y_train,train_pred))
print('train precision :- ',precision_score(y_train,train_pred))
print('train recall :- ',recall_score(y_train,train_pred))

train accu :-  0.9676912721561588
train confusion matrix :- 
 [[3861    4]
 [ 140  452]]
train precision :-  0.9912280701754386
train recall :-  0.7635135135135135


In [ ]:
print('Test acc :- ',accuracy_score(y_test,test_pred))
print('Test confusion matrix :- \n',confusion_matrix(y_test,test_pred))
print('Test precision :- ',precision_score(y_test,test_pred))
print('Test recall :- ',recall_score(y_test,test_pred))

Test acc :-  0.9668161434977578
Test confusion matrix :- 
 [[960   0]
 [ 37 118]]
Test precision :-  1.0
Test recall :-  0.7612903225806451


### Building a Predictive System

In [ ]:
input_data = ["i am going to delhi."]
data = feature_extraction.transform(input_data)
prediction = model.predict(data)
if prediction[0] == 1:
  print('Spam mail')
else:
  print('ham mail')

ham mail
